<?php

namespace App\Libraries;

/**
 * Demonstration data for the transplant UI.
 *
 * Converted verbatim from the `js/data.js` of the HTML prototype, which was
 * itself a copy of the React app's `src/data.ts`. The prototype kept this in
 * memory and lost it on reload; here it seeds the per-session working copy
 * held by {@see UiStore}, so nothing is written to the database.
 *
 * Swap the four methods below for `App\Models\*` queries to put the screens on
 * real data — the views take plain arrays and do not care where they come from.
 */
final class UiSeed
{
    /**
     * @return array{
     *     initialRecipients: list<array<string, mixed>>,
     *     initialDonors: list<array<string, mixed>>,
     *     initialPairs: list<array<string, mixed>>,
     *     initialMRPs: list<array{id: string, name: string}>
     * }
     */
    public static function all(): array
    {
        return [
            'initialRecipients' => [
                [
                    'id' => 'R-001',
                    'type' => 'recipient',
                    'organ' => 'kidney',
                    'name' => 'Sarah Al-Mansouri',
                    'age' => 42,
                    'bloodType' => 'A',
                    'hospital' => 'King Faisal Specialist Hospital',
                    'dateRegistered' => '2026-01-15',
                    'urgency' => 'high',
                    'diagnosis' => 'End-stage renal disease (ESRD)',
                    'phone' => '+966 50 123 4567',
                    'address' => 'Riyadh, Saudi Arabia',
                    'notes' => 'Patient currently on hemodialysis 3x/week. Compliant with medication regimen. Potential living donor (brother) under evaluation.',
                    'labTests' => [
                        [
                            'id' => 'r1-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 8 mL/min/1.73m²',
                            'date' => '2026-08-20',
                        ],
                        [
                            'id' => 'r1-2',
                            'name' => 'Crossmatch',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-08-22',
                        ],
                        [
                            'id' => 'r1-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A2, B44, DR7',
                            'date' => '2026-08-18',
                        ],
                        [
                            'id' => 'r1-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-08-19',
                        ],
                        [
                            'id' => 'r1-5',
                            'name' => 'Cardiac Clearance',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r1-6',
                            'name' => 'Renal Ultrasound',
                            'status' => 'completed',
                            'result' => 'Bilateral cortical atrophy',
                            'date' => '2026-08-21',
                        ],
                    ],
                ],
                [
                    'id' => 'R-002',
                    'type' => 'recipient',
                    'organ' => 'kidney',
                    'name' => 'Mohammed Al-Rashid',
                    'age' => 58,
                    'bloodType' => 'O',
                    'hospital' => 'National Guard Health Affairs',
                    'dateRegistered' => '2025-11-02',
                    'urgency' => 'critical',
                    'diagnosis' => 'Diabetic nephropathy, ESRD',
                    'phone' => '+966 55 987 6543',
                    'address' => 'Jeddah, Saudi Arabia',
                    'notes' => 'Priority listing. Deteriorating condition. Cardiac issue flagged — review required before surgical clearance.',
                    'pairedDonorId' => 'D-002',
                    'labTests' => [
                        [
                            'id' => 'r2-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 5 mL/min/1.73m²',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'r2-2',
                            'name' => 'Crossmatch',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-09-02',
                        ],
                        [
                            'id' => 'r2-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A1, B8, DR3',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'r2-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'r2-5',
                            'name' => 'Cardiac Clearance',
                            'status' => 'flagged',
                            'result' => 'Moderate LV dysfunction — cardiology review required',
                            'date' => '2026-09-03',
                            'notes' => 'Echocardiogram EF 40%. Pending cardiology sign-off before surgery.',
                        ],
                        [
                            'id' => 'r2-6',
                            'name' => 'Renal Ultrasound',
                            'status' => 'completed',
                            'result' => 'Small echogenic kidneys bilaterally',
                            'date' => '2026-09-01',
                        ],
                    ],
                ],
                [
                    'id' => 'R-003',
                    'type' => 'recipient',
                    'organ' => 'kidney',
                    'name' => 'Fatima Hassan',
                    'age' => 35,
                    'bloodType' => 'B',
                    'hospital' => 'King Abdulaziz University Hospital',
                    'dateRegistered' => '2026-03-20',
                    'urgency' => 'medium',
                    'diagnosis' => 'IgA nephropathy',
                    'phone' => '+966 53 456 7890',
                    'address' => 'Mecca, Saudi Arabia',
                    'notes' => 'Younger patient, excellent surgical candidate. Awaiting living donor workup completion.',
                    'pairedDonorId' => 'D-003',
                    'labTests' => [
                        [
                            'id' => 'r3-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 14 mL/min/1.73m²',
                            'date' => '2026-09-05',
                        ],
                        [
                            'id' => 'r3-2',
                            'name' => 'Crossmatch',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r3-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A3, B7, DR15',
                            'date' => '2026-09-04',
                        ],
                        [
                            'id' => 'r3-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-04',
                        ],
                        [
                            'id' => 'r3-5',
                            'name' => 'Cardiac Clearance',
                            'status' => 'completed',
                            'result' => 'Cleared for surgery',
                            'date' => '2026-09-05',
                        ],
                        [
                            'id' => 'r3-6',
                            'name' => 'Renal Ultrasound',
                            'status' => 'pending',
                        ],
                    ],
                ],
                [
                    'id' => 'R-004',
                    'type' => 'recipient',
                    'organ' => 'kidney',
                    'name' => 'Omar Khalil',
                    'age' => 67,
                    'bloodType' => 'AB',
                    'hospital' => 'Prince Sultan Military Medical City',
                    'dateRegistered' => '2026-06-10',
                    'urgency' => 'low',
                    'diagnosis' => 'Hypertensive nephrosclerosis',
                    'phone' => '+966 54 321 0987',
                    'address' => 'Medina, Saudi Arabia',
                    'notes' => 'Stable on peritoneal dialysis. Not in immediate danger. Full workup still pending.',
                    'labTests' => [
                        [
                            'id' => 'r4-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 18 mL/min/1.73m²',
                            'date' => '2026-08-15',
                        ],
                        [
                            'id' => 'r4-2',
                            'name' => 'Crossmatch',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r4-3',
                            'name' => 'HLA Typing',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r4-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-08-15',
                        ],
                        [
                            'id' => 'r4-5',
                            'name' => 'Cardiac Clearance',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r4-6',
                            'name' => 'Renal Ultrasound',
                            'status' => 'pending',
                        ],
                    ],
                ],
                [
                    'id' => 'R-005',
                    'type' => 'recipient',
                    'organ' => 'kidney',
                    'name' => 'Noura Al-Saud',
                    'age' => 29,
                    'bloodType' => 'A',
                    'hospital' => 'King Faisal Specialist Hospital',
                    'dateRegistered' => '2026-04-08',
                    'urgency' => 'high',
                    'diagnosis' => 'Polycystic kidney disease (PKD)',
                    'phone' => '+966 56 654 3210',
                    'address' => 'Riyadh, Saudi Arabia',
                    'notes' => 'Family history of PKD. Sister evaluated as potential living donor — crossmatch results awaited.',
                    'labTests' => [
                        [
                            'id' => 'r5-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 11 mL/min/1.73m²',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'r5-2',
                            'name' => 'Crossmatch',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-09-09',
                        ],
                        [
                            'id' => 'r5-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A24, B35, DR4',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'r5-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'r5-5',
                            'name' => 'Cardiac Clearance',
                            'status' => 'completed',
                            'result' => 'Cleared for surgery',
                            'date' => '2026-09-09',
                        ],
                        [
                            'id' => 'r5-6',
                            'name' => 'Renal Ultrasound',
                            'status' => 'completed',
                            'result' => 'Massively enlarged polycystic kidneys',
                            'date' => '2026-09-08',
                        ],
                    ],
                ],
                [
                    'id' => 'R-101',
                    'type' => 'recipient',
                    'organ' => 'liver',
                    'name' => 'Ahmad Saleh',
                    'age' => 52,
                    'bloodType' => 'O',
                    'hospital' => 'King Faisal Specialist Hospital',
                    'dateRegistered' => '2026-02-14',
                    'urgency' => 'critical',
                    'diagnosis' => 'Hepatocellular carcinoma on cirrhosis (HCC/HBV)',
                    'phone' => '+966 50 111 2222',
                    'address' => 'Riyadh, Saudi Arabia',
                    'notes' => 'MELD score 32. Within Milan criteria. Living related donation planned — right lobe from son.',
                    'pairedDonorId' => 'D-101',
                    'labTests' => [
                        [
                            'id' => 'r101-1',
                            'name' => 'MELD Score',
                            'status' => 'completed',
                            'result' => '32',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'r101-2',
                            'name' => 'LFTs (ALT / AST / Bilirubin)',
                            'status' => 'completed',
                            'result' => 'ALT 210 U/L, AST 280 U/L, Bili 8.4 mg/dL',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'r101-3',
                            'name' => 'INR / Coagulation',
                            'status' => 'completed',
                            'result' => 'INR 2.1',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'r101-4',
                            'name' => 'Crossmatch',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'r101-5',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'HBsAg positive, HBV DNA 1200 IU/mL — on antivirals',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'r101-6',
                            'name' => 'Liver CT / MRI',
                            'status' => 'completed',
                            'result' => 'Single HCC lesion 2.8 cm, no vascular invasion',
                            'date' => '2026-09-05',
                        ],
                        [
                            'id' => 'r101-7',
                            'name' => 'Cardiac Clearance',
                            'status' => 'pending',
                        ],
                    ],
                ],
                [
                    'id' => 'R-102',
                    'type' => 'recipient',
                    'organ' => 'liver',
                    'name' => 'Layla Qasim',
                    'age' => 44,
                    'bloodType' => 'A',
                    'hospital' => 'King Abdulaziz University Hospital',
                    'dateRegistered' => '2026-05-30',
                    'urgency' => 'high',
                    'diagnosis' => 'Primary biliary cholangitis (PBC), decompensated',
                    'phone' => '+966 53 333 4444',
                    'address' => 'Jeddah, Saudi Arabia',
                    'notes' => 'Refractory ascites, recurrent spontaneous bacterial peritonitis. MELD 26.',
                    'labTests' => [
                        [
                            'id' => 'r102-1',
                            'name' => 'MELD Score',
                            'status' => 'completed',
                            'result' => '26',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'r102-2',
                            'name' => 'LFTs (ALT / AST / Bilirubin)',
                            'status' => 'completed',
                            'result' => 'ALT 88 U/L, AST 102 U/L, Bili 6.1 mg/dL',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'r102-3',
                            'name' => 'INR / Coagulation',
                            'status' => 'completed',
                            'result' => 'INR 1.7',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'r102-4',
                            'name' => 'Crossmatch',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r102-5',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'r102-6',
                            'name' => 'Liver CT / MRI',
                            'status' => 'completed',
                            'result' => 'Cirrhotic liver with moderate ascites, no HCC',
                            'date' => '2026-08-28',
                        ],
                        [
                            'id' => 'r102-7',
                            'name' => 'Cardiac Clearance',
                            'status' => 'completed',
                            'result' => 'Cleared for surgery',
                            'date' => '2026-09-05',
                        ],
                    ],
                ],
                [
                    'id' => 'R-103',
                    'type' => 'recipient',
                    'organ' => 'liver',
                    'name' => 'Tariq Mahmoud',
                    'age' => 61,
                    'bloodType' => 'B',
                    'hospital' => 'National Guard Health Affairs',
                    'dateRegistered' => '2026-07-01',
                    'urgency' => 'medium',
                    'diagnosis' => 'Non-alcoholic steatohepatitis (NASH) cirrhosis',
                    'phone' => '+966 55 555 6666',
                    'address' => 'Dammam, Saudi Arabia',
                    'notes' => 'Controlled T2DM. Weight loss program completed. MELD 18. Full workup partially pending.',
                    'labTests' => [
                        [
                            'id' => 'r103-1',
                            'name' => 'MELD Score',
                            'status' => 'completed',
                            'result' => '18',
                            'date' => '2026-09-12',
                        ],
                        [
                            'id' => 'r103-2',
                            'name' => 'LFTs (ALT / AST / Bilirubin)',
                            'status' => 'completed',
                            'result' => 'ALT 55 U/L, AST 67 U/L, Bili 2.8 mg/dL',
                            'date' => '2026-09-12',
                        ],
                        [
                            'id' => 'r103-3',
                            'name' => 'INR / Coagulation',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r103-4',
                            'name' => 'Crossmatch',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r103-5',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'r103-6',
                            'name' => 'Liver CT / MRI',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'r103-7',
                            'name' => 'Cardiac Clearance',
                            'status' => 'pending',
                        ],
                    ],
                ],
            ],
            'initialDonors' => [
                [
                    'id' => 'D-001',
                    'type' => 'donor',
                    'organ' => 'kidney',
                    'name' => 'Khalid Al-Mansouri',
                    'age' => 38,
                    'bloodType' => 'A',
                    'hospital' => 'King Faisal Specialist Hospital',
                    'donationType' => 'living',
                    'relationship' => 'Brother of recipient R-001',
                    'phone' => '+966 50 123 9999',
                    'address' => 'Riyadh, Saudi Arabia',
                    'notes' => 'Motivated living donor. Healthy. Full workup initiated — renal CT pending.',
                    'labTests' => [
                        [
                            'id' => 'd1-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 88 mL/min/1.73m²',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'd1-2',
                            'name' => 'Crossmatch (vs R-001)',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-09-02',
                        ],
                        [
                            'id' => 'd1-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A2, B44, DR11',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'd1-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'd1-5',
                            'name' => 'Renal CT Angiogram',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd1-6',
                            'name' => 'Cardiac Clearance',
                            'status' => 'completed',
                            'result' => 'Cleared for surgery',
                            'date' => '2026-09-03',
                        ],
                        [
                            'id' => 'd1-7',
                            'name' => 'Psychiatric Evaluation',
                            'status' => 'completed',
                            'result' => 'Cleared — no concerns identified',
                            'date' => '2026-09-04',
                        ],
                    ],
                ],
                [
                    'id' => 'D-002',
                    'type' => 'donor',
                    'organ' => 'kidney',
                    'name' => 'Aisha Mohammed',
                    'age' => 45,
                    'bloodType' => 'O',
                    'hospital' => 'National Guard Health Affairs',
                    'donationType' => 'living',
                    'relationship' => 'Spouse of recipient R-002',
                    'phone' => '+966 55 888 7654',
                    'address' => 'Jeddah, Saudi Arabia',
                    'notes' => 'Crossmatch with R-002 completed successfully. Psychiatric clearance pending.',
                    'pairedRecipientId' => 'R-002',
                    'labTests' => [
                        [
                            'id' => 'd2-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 75 mL/min/1.73m²',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'd2-2',
                            'name' => 'Crossmatch (vs R-002)',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-09-02',
                        ],
                        [
                            'id' => 'd2-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A1, B35, DR7',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'd2-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-01',
                        ],
                        [
                            'id' => 'd2-5',
                            'name' => 'Renal CT Angiogram',
                            'status' => 'completed',
                            'result' => 'Favorable single renal arteries bilaterally',
                            'date' => '2026-09-05',
                        ],
                        [
                            'id' => 'd2-6',
                            'name' => 'Cardiac Clearance',
                            'status' => 'completed',
                            'result' => 'Cleared for surgery',
                            'date' => '2026-09-04',
                        ],
                        [
                            'id' => 'd2-7',
                            'name' => 'Psychiatric Evaluation',
                            'status' => 'pending',
                        ],
                    ],
                ],
                [
                    'id' => 'D-003',
                    'type' => 'donor',
                    'organ' => 'kidney',
                    'name' => 'Ibrahim Hassan',
                    'age' => 30,
                    'bloodType' => 'B',
                    'hospital' => 'King Abdulaziz University Hospital',
                    'donationType' => 'living',
                    'relationship' => 'Brother of recipient R-003',
                    'phone' => '+966 53 777 8888',
                    'address' => 'Mecca, Saudi Arabia',
                    'notes' => 'Healthy 30-year-old male. Excellent surgical candidate. CT angiogram pending.',
                    'pairedRecipientId' => 'R-003',
                    'labTests' => [
                        [
                            'id' => 'd3-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 95 mL/min/1.73m²',
                            'date' => '2026-09-06',
                        ],
                        [
                            'id' => 'd3-2',
                            'name' => 'Crossmatch (vs R-003)',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd3-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A3, B7, DR15',
                            'date' => '2026-09-06',
                        ],
                        [
                            'id' => 'd3-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-06',
                        ],
                        [
                            'id' => 'd3-5',
                            'name' => 'Renal CT Angiogram',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd3-6',
                            'name' => 'Cardiac Clearance',
                            'status' => 'completed',
                            'result' => 'Cleared for surgery',
                            'date' => '2026-09-07',
                        ],
                        [
                            'id' => 'd3-7',
                            'name' => 'Psychiatric Evaluation',
                            'status' => 'completed',
                            'result' => 'Cleared',
                            'date' => '2026-09-07',
                        ],
                    ],
                ],
                [
                    'id' => 'D-004',
                    'type' => 'donor',
                    'organ' => 'kidney',
                    'name' => 'Nadia Al-Rashid',
                    'age' => 55,
                    'bloodType' => 'O',
                    'hospital' => 'Prince Sultan Military Medical City',
                    'donationType' => 'deceased',
                    'phone' => 'N/A',
                    'address' => 'Medina, Saudi Arabia',
                    'notes' => 'Deceased donor. Brain death confirmed. Next-of-kin consent obtained. Organs viable for allocation.',
                    'labTests' => [
                        [
                            'id' => 'd4-1',
                            'name' => 'eGFR / Creatinine',
                            'status' => 'completed',
                            'result' => 'eGFR 62 mL/min/1.73m²',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'd4-2',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'd4-3',
                            'name' => 'HLA Typing',
                            'status' => 'completed',
                            'result' => 'A11, B51, DR1',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'd4-4',
                            'name' => 'Renal Ultrasound',
                            'status' => 'completed',
                            'result' => 'Normal parenchyma bilaterally',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'd4-5',
                            'name' => 'Blood Cultures',
                            'status' => 'completed',
                            'result' => 'No growth at 48h',
                            'date' => '2026-09-10',
                        ],
                    ],
                ],
                [
                    'id' => 'D-101',
                    'type' => 'donor',
                    'organ' => 'liver',
                    'name' => 'Yusuf Al-Saleh',
                    'age' => 40,
                    'bloodType' => 'O',
                    'hospital' => 'King Faisal Specialist Hospital',
                    'donationType' => 'living',
                    'relationship' => 'Son of recipient R-101',
                    'phone' => '+966 50 222 3333',
                    'address' => 'Riyadh, Saudi Arabia',
                    'notes' => 'Right lobe donation planned. Adequate future liver remnant confirmed. Cardiac clearance pending.',
                    'pairedRecipientId' => 'R-101',
                    'labTests' => [
                        [
                            'id' => 'd101-1',
                            'name' => 'LFTs (ALT / AST / Bilirubin)',
                            'status' => 'completed',
                            'result' => 'ALT 28 U/L, AST 22 U/L, Bili 0.8 mg/dL',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'd101-2',
                            'name' => 'Liver Volumetry (CT)',
                            'status' => 'completed',
                            'result' => 'Right lobe 62%, future remnant 38% — adequate',
                            'date' => '2026-09-09',
                        ],
                        [
                            'id' => 'd101-3',
                            'name' => 'Crossmatch (vs R-101)',
                            'status' => 'completed',
                            'result' => 'Negative',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'd101-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'HBsAg negative, Anti-HBs positive (immune)',
                            'date' => '2026-09-08',
                        ],
                        [
                            'id' => 'd101-5',
                            'name' => 'Liver Biopsy',
                            'status' => 'completed',
                            'result' => 'No steatosis, no fibrosis — normal parenchyma',
                            'date' => '2026-09-11',
                        ],
                        [
                            'id' => 'd101-6',
                            'name' => 'Psychiatric Evaluation',
                            'status' => 'completed',
                            'result' => 'Cleared',
                            'date' => '2026-09-07',
                        ],
                        [
                            'id' => 'd101-7',
                            'name' => 'Cardiac Clearance',
                            'status' => 'pending',
                        ],
                    ],
                ],
                [
                    'id' => 'D-102',
                    'type' => 'donor',
                    'organ' => 'liver',
                    'name' => 'Mariam Khalil',
                    'age' => 36,
                    'bloodType' => 'A',
                    'hospital' => 'King Abdulaziz University Hospital',
                    'donationType' => 'living',
                    'relationship' => 'Sister of recipient R-102',
                    'phone' => '+966 53 444 5555',
                    'address' => 'Jeddah, Saudi Arabia',
                    'notes' => 'Preliminary evaluation positive. Full workup in progress — volumetry and biopsy pending.',
                    'labTests' => [
                        [
                            'id' => 'd102-1',
                            'name' => 'LFTs (ALT / AST / Bilirubin)',
                            'status' => 'completed',
                            'result' => 'Within normal limits',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'd102-2',
                            'name' => 'Liver Volumetry (CT)',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd102-3',
                            'name' => 'Crossmatch (vs R-102)',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd102-4',
                            'name' => 'Virology Panel (HIV, HBV, HCV)',
                            'status' => 'completed',
                            'result' => 'Non-reactive',
                            'date' => '2026-09-10',
                        ],
                        [
                            'id' => 'd102-5',
                            'name' => 'Liver Biopsy',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd102-6',
                            'name' => 'Psychiatric Evaluation',
                            'status' => 'pending',
                        ],
                        [
                            'id' => 'd102-7',
                            'name' => 'Cardiac Clearance',
                            'status' => 'pending',
                        ],
                    ],
                ],
            ],
            'initialPairs' => [
                [
                    'id' => 'P-001',
                    'organ' => 'kidney',
                    'status' => 'active',
                    'recipientId' => 'R-002',
                    'donorId' => 'D-002',
                    'createdDate' => '2026-09-03',
                    'scheduledDate' => '2026-09-25',
                    'notes' => 'Awaiting cardiac clearance for recipient (R-002) before confirming surgery date. All other workups complete.',
                ],
                [
                    'id' => 'P-002',
                    'organ' => 'kidney',
                    'status' => 'scheduled',
                    'recipientId' => 'R-003',
                    'donorId' => 'D-003',
                    'createdDate' => '2026-09-07',
                    'scheduledDate' => '2026-10-05',
                    'notes' => 'Surgery scheduled for Oct 5. Crossmatch and CT angiogram still pending on donor side.',
                ],
                [
                    'id' => 'P-101',
                    'organ' => 'liver',
                    'status' => 'active',
                    'recipientId' => 'R-101',
                    'donorId' => 'D-101',
                    'createdDate' => '2026-09-09',
                    'notes' => 'Living related right lobe donation. Recipient and donor cardiac clearance both pending. Surgery date TBD.',
                ],
            ],
            'initialMRPs' => [
                [
                    'id' => 'MRP-001',
                    'name' => 'Dr. Hassan Al-Otaibi',
                ],
                [
                    'id' => 'MRP-002',
                    'name' => 'Dr. Sara Mahmoud',
                ],
                [
                    'id' => 'MRP-003',
                    'name' => 'Dr. Khaled Ibrahim',
                ],
            ],
        ];
    }

    /** @return list<array<string, mixed>> */
    public static function recipients(): array
    {
        return self::all()['initialRecipients'];
    }

    /** @return list<array<string, mixed>> */
    public static function donors(): array
    {
        return self::all()['initialDonors'];
    }

    /** @return list<array<string, mixed>> */
    public static function pairs(): array
    {
        return self::all()['initialPairs'];
    }

    /** @return list<array{id: string, name: string}> */
    public static function mrps(): array
    {
        return self::all()['initialMRPs'];
    }
}
